server.port=${PT_SERVICE_PORT:8080}
traverser.concurrencyDegree=10
traverser.omitEmptyResults=true
traverser.preferProvServiceFromConnectors=false
demoValidityVerifier.authHeader=Bearer full_access_token